### ISSUE TITLE
Doesn't work on Zorin OS

### ISSUE THREAD

**Issue by Charliecoop** [ardba/proton_aoe2de_mpfix#11]
Instruction's/Readme isn't clear enough for me. I don't know what I should be changing in the launch options to ensure what the location should be for Zorin OS which uses flatpack/flatpak which doesn't seem to use defaults that this code assumes. I've included a screenshot which causes confusion (what is the Steam location this readme calls for?)?

https://imgur.com/a/DES2G4e

**Comment by aragilar** [comment]
Looks like you're using snap to install steam, for some reason it saves the data using a slightly different scheme, but the important directory relative to the directory in the screenshot is `steamapps/compatdata/$APPID/pfx/drive_c/windows/system32` (see https://github.com/ardba/proton_aoe2de_mpfix/blob/main/run.sh#L20). That should give you enough context to be able to run the commands manually, so you can then understand what you need to modify to get the script running on your system.

**Comment by Charliecoop** [comment]
this didn't work for me - I'm doing something wrong. I managed to find a YouTube video and followed the terminal commands in that to do a similar thing. Thanks for your help anyway!
