### ISSUE TITLE
Problem with Second Steam Library Location

### ISSUE THREAD

**Issue by sashokbg** [ardba/proton_aoe2de_mpfix#9]
Hello,

On my current setup I have a second steam library configured on another drive - I like to have a fast library on SSD and slower on HDD.

The problem is that the second library, where AO2 DE is installed has a different directory path structure.

Essentially the system32 dir becomes ~/my-lib/**steamlibrary/steamapps/compatdata/813780/pfx/drive_c/windows/system32**

The simple solution would be to provide a var that can override system32 location, but I am thinking if it is possible to have a better solution that automatically finds where the game is installed and if it is in a secondary library adapt accordingly ?

Thank you for your tool ! :)

**Comment by sashokbg** [comment]
I added a PR #10 to address the issue :)

**Comment by ardba** [comment]
Hello,

Thank you for your contribution, and sorry for my late reply. I will merge right now

**Comment by sashokbg** [comment]
Hello @ardba no problem :) let me know if it needs any additional tweaks !
